### ISSUE TITLE
Change controller attributes to axis attributes

### ISSUE THREAD

**Issue by reszelaz** [ALBA-Synchrotron/sardana-limaccd#10]
Attributes like `SavingNextNumber` would be easier to access to the user if these were axis attributes instead of controller attributes. If you agree I can make a PR.

**Comment by rhomspuron** [comment]
The idea is to have the controller for the configuration and the channel is only use for the measurement group. We used as controller name the same than the detector eg: mythen and for the axis mythen_image.

**Comment by rhomspuron** [comment]
One question, in which case the user need to change the saving next number?

**Comment by reszelaz** [comment]
@rhomspuron thanks for the reply!

> The idea is to have the controller for the configuration and the channel is only use for the measurement group. 

What is the benefit of having it separated? IMHO it adds complexity.

> One question, in which case the user need to change the saving next number?

We needed to access it in Spock when commissioning the detector by manual interaction.

Later in the macro we need to access to the controller object in order to set it:

```python
moke_detector = self.getExpChannel(moke_detector_name)
moke_detector_ctrl = moke_detector.getControllerObj()
moke_detector_ctrl.savingnextnumber = 0
```

Well, this attribute is just an example, there are others e.g. the ones related to the header which may be interesting to be set in a macro.

**Comment by rhomspuron** [comment]
> We needed to access it in Spock when commissioning the detector by manual interaction.

To change the saving next number can generate problem depending of the overwrite policy used.  IMHO this is not necessary to change by hand, the system (Sardana, SEP2, scan framework & LimaCCDs) should do the work. 

On the other hand this can generate confusion on the 1D LimaCCDs, because you will have more than one channel on the same controller, and the saving number is the same for all of them. This is for all other attributes. 

If you want to change this parameter on the macro you can do it: 
```
moke_detector = self.getController('moke_detector_name)
mode_detector.savingnextnumber = 0 
```

**Comment by reszelaz** [comment]
> IMHO this is not necessary to change by hand, the system (Sardana, SEP2, scan framework & LimaCCDs) should do the work.

If there is no need to write it, what about changing it to read only attribute?

> On the other hand this can generate confusion on the 1D LimaCCDs, because you will have more than one channel on the same controller, and the saving number is the same for all of them.

I thought this was not foreseen for the LimaCCDs controller. I assumed that from the `MaxDevice = 1`. This property is still not preventing you from defining more axes on the controller (I think this is some of the unfinished implementations in Sardana), but the idea behind it was exactly this (see this old [documentation](https://sardana-controls.org/devel/api/tango_device_pool.html?highlight=maxdevice#the-maxdevice-property)).

But if you want to have more axes and all these attributes affect all the axes, then of course these fits better to the controller attributes.

> If you want to change this parameter on the macro you can do it:

Here you need to know the controller name. And you need to know that the concept of the controller exists... :) The whole issue was about making it simpler.

**Comment by rhomspuron** [comment]
> I thought this was not foreseen for the LimaCCDs controller. I assumed that from the `MaxDevice = 1`. This property is still not preventing you from defining more axes on the controller (I think this is some of the unfinished implementations in Sardana), but the idea behind it was exactly this (see this old [documentation](https://sardana-controls.org/devel/api/tango_device_pool.html?highlight=maxdevice#the-maxdevice-property)).
> 
> But if you want to have more axes and all these attributes affect all the axes, then of course these fits better to the controller attributes.

The point is to have the same API for the 1D and the 2D. See PR #11 


> Here you need to know the controller name. And you need to know that the concept of the controller exists... :) The whole issue was about making it simpler.

For that reason we use as name of controller the same than the detector, in the case of the 2D you will have only one axis as first approximation, but in the case of the 1D you will have the same number of axes than detectors.

**Comment by reszelaz** [comment]
In this case, I would remove from the controller the `MaxDevice=1` which confused me.

> but in the case of the 1D you will have the same number of axes than detectors.

Yes, which does not always imply multiple axes.

I'm happy with the clarification. Thanks a lot!

**Comment by rhomspuron** [comment]
> In this case, I would remove from the controller the `MaxDevice=1` which confused me.

In the case of a 2D detector, should be 1, in the case of the 1D can be more than 1
