### ISSUE TITLE
Proposal for Lima configuration inside sardana

### ISSUE THREAD

**Issue by tiagocoutinho** [ALBA-Synchrotron/sardana-limaccd#9]
This is a request for enhancement to be able to use lima inside sardana in a useful way.

Some features of the MG are decoupled from the sardana scan infrastructure.
For example, the *ScanDir* / *ScanFile* environment used in scans has no connection with *ValueRefPattern* in the 2D channel.
We want to propose and agree on a set of tools that close this gap and allow for coherent configuration.

The proposal is just an initial starting point. Every point is fully open for discussion/change/removal.

## Lima 2D Controller

* missing check: ensure that an acquisition can only be performed if `valueref == True`
* missing feature: internal-trigger-multi

## MS configuration

Before any scan is executed, validation and configuration needs to be made to both active the measurement group and the lima 2d channels enabled.
We propose:
* a *general hook* (called `lima_hook`) should ensure both lima channels and measurement group are properly configured
* a set of macros to change the lima configuration:
  * a `lima_reconfig` - ensures the lima system is properly configured (ie, `lima_hook` is registered as a general hook plus any other config that we find necessary)
  * `set_lima_conf` - configures the specified detector with the given configuration (ex: `set_lima_config xpress3_image prefix XP3_`)
  * `get_lima_conf` - shows the active lima config for the given detector
  * `def_lima` registers the given detector (ex: `def_lima xpress3_image prefix=XP3_ index=05d`)

The internal lima configuration structure could look something like this:
```json
{
  "detectors": {
    "xpress3_image": {
      "prefix": "XP3_",
      "suffix": ".h5",
      "index": "05d",
      "scan_sub_dir": "scan_{ScanID:04d}",
      "directory": "xp3"
    },

    "mythen": {
      "prefix": "myth_",
      "suffix": ".edf",
      "index": "04d",
      "scan_sub_dir": "scan_{ScanID:04d}",
      "directory": "mythen"
    },
  }
```

With the above example in mind, and imagining the `ScanDir=/tmp; ScanID=34`, before a scan is done, the `lima_hook` would ensure that:
* the detectors *ValueRefPattern* in the measurement group follows :`<ScanDir>/<directory>/<scan_sub_dir>/<prefix>{index:<index>}<suffix>`. Example `/tmp/xp3/scan_0035/XP3_{index:05d}h5`
* ensure `ValueRefEnabled=True`
* the above directory exists and is writable
* any other checks deemed appropriate

Open question:
Where to store the configuration? 
1. sardana settings as they are now
2. sardana settings with redis backend (see sardana PR [1200](https://github.com/sardana-org/sardana/pull/1200))
3. use a redis db directly

**Comment by tiagocoutinho** [comment]
> Open question:
Where to store the configuration?

IHMO:
1. is simple, existing solution but is quite limited in the type of things we can store.
2. we should not depend on features that are not in sardana yet (ex: the above PR has been open for 5 months with nobody to review it). Also, since it hides redis, we loose some of the redis capabilities
3. for me the most powerful. It would require some more code and setup on the beamline. The big advantage I see is that another client (ex: a simple GUI) can be used to reconfigure lima

**Comment by rhomspuron** [comment]
IMHO:
1. is simple, but implement a GUI to change the values based on the current environment is not nice.
2. could be a good moment to evaluate the PR and start to use it as first implementation. 
3. If we have the option 2, we can create a GUI based on redis. I prefer to have a solution on the system and not out of the system if it is possible.

**Comment by reszelaz** [comment]
Nice! What about having a meeting and discussing this issue?
I think it would be of interest of all to implement it in a way as much as possible independent of Lima, so other Sardana users could benefit of this. There is a similar discussion in https://github.com/sardana-org/sardana/issues/1500.
